config/routes.rb
Stories::Application.routes.draw do

 

  mount RedactorRails::Engine => '/redactor_rails'

  resources :posts

  devise_for :users

  root :to => 'posts#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  ActiveAdmin.routes(self)

  

  get "static_pages/about"
  get "static_pages/membership"
  get "static_pages/curious"

  get "users/show"

  match '/users/:id', :to => 'users#show', :as => :user

  

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  attr_accessible :content, :title, :image, :remote_image_url,
  :user_id, :slug

  mount_uploader :image, ImageUploader

  belongs_to :user

  validates :user_id, presence: true
  validates :content, presence: true
end

app/models/redactor_rails/asset.rb
class RedactorRails::Asset < ActiveRecord::Base
  include RedactorRails::Orm::ActiveRecord::AssetBase
  delegate :url, :current_path, :size, :content_type, :filename, :to => :data
  validates_presence_of :data
end

app/models/redactor_rails/document.rb
class RedactorRails::Document < RedactorRails::Asset
  mount_uploader :data, RedactorRailsDocumentUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/redactor_rails/picture.rb
class RedactorRails::Picture < RedactorRails::Asset
  mount_uploader :data, RedactorRailsPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  extend FriendlyId
  friendly_id :last_name, use: :slugged
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name,
  :last_name, :twitter, :bio
  # attr_accessible :title, :body

  has_many :posts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/image_controller.rb
class ImageController < ApplicationController
  def new
    @uploader = Post.new.image
    @uploader.success_action_redirect = new_post_url
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json

  before_filter :authenticate_user!, except: [ :index, :show ] 
  before_filter :have_footer, except: [:index]

  def index
    @posts = Post.all.sort { |p1, p2| p2.created_at <=> p1.created_at }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  def have_footer
    @have_footer = true
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	
	def new
	    super
    end

    def create
    	if params["secret"] == "yeats"
			super
		end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  before_filter :have_footer 

  def about
  end

  def membership
  end

  def curious
  end

  def have_footer
    @have_footer = true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :have_footer 
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def have_footer
    @have_footer = true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer"><h1 id="footer_logo" class="normal"><%= link_to "THE FILADELFIAN", root_path %></h1><div>
<div id="copyright" class="footer"> © 2013 Filadelfian.</div>

app/views/layouts/_header.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <ul class="nav pull-right">
    	<li class="dropdown">
		    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
		      <div id="dropdown">F</div>
		    </a>
		    <ul class="dropdown-menu">
		    <% if user_signed_in? %>
			    <li><%= link_to('My Profile', current_user) %></li>
			    <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>        
			<% else %>
			    <li><%= link_to('Login', new_user_session_path) %></li>
			    <li><%= link_to('Membership', static_pages_membership_path) %></li>
			    <li><%= link_to('Curious?', static_pages_curious_path) %></li>
		    <% end %>
		    </ul>
		</li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Filadelfian</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag "/assets/favicon.ico" %>
  <%= favicon_link_tag '/assets/apple-touch-icon.png', :rel => 'apple-touch-icon', :type => 'image/png' %>
</head>
<body>

    <!-- Facebook -->
	<div id="fb-root"></div>

	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
	<!-- Facebook -->

	<!-- Twitter -->
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
	<!-- Twitter -->

	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
	</div>
	<div class="push"></div>
	<div class="footer">
		<%= render 'layouts/footer' if @have_footer %>
	</div>

    <!-- Google analytics -->
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-40677157-1', 'filadelfian.com');
	  ga('send', 'pageview');
	</script>
	<!-- Google analytics -->

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post, :html => { :multipart => true }) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :class => "post_title_input" %>
  </div>
  
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content, :class => "post_content_input redactor" %>
  </div>
  <div class="actions">
    <%= f.submit "Publish", :class => "btn btn-custom-grey" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div id="logo"><%= link_to "THE FILADELFIAN", root_path %></div>
<div id="tagline">Sharp Writing</div>
<br />

<% if user_signed_in? %>
    <div id="publish_link" class="purple_hover">
        <%= link_to image_tag("fountainpen.svg"), new_post_path, :method => :get %>
        <%= link_to "PUBLISH SOMETHING NEW", new_post_path, :method => :get %>
    </div>
<% end %>

<br/>
<br/>
<br/>

<div class="content">
    <% @posts.each do |post| %>
        <div class="post">
            <div class="post_heading">
                <div class="post_date">
                    <%= Time.at(post.created_at.to_time.to_i).strftime("%B %e, %Y ") %>
                </div> 
                <div class="post_title purple_hover">
                	<%= link_to post.title, post %>
                </div>
                <div class="post_author purple_hover">
                  <%= link_to "#{post.user.first_name} #{post.user.last_name}", post.user %>
                </div>
            </div> 
            <div class="post_content">
            <%= simple_format(post.content[0..300] + "...") %>
            </div>
        </div>        
    <% end %>
</div>

app/views/posts/new.html.erb
<h1 class="normal">New piece</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="content">
	<p id="notice"><%= notice %></p>
    <div class="main_post_heading">
		<div class="post_date">
		  <%= Time.at(
		    @post.created_at.to_time.to_i
		    ).strftime("%B %e, %Y ") %>
		</div> 
		<div class="post_title">
		  <p><%= @post.title %></p>
		</div> 
		<div class="post_author purple_hover">
		  <%= link_to "#{@post.user.first_name} #{@post.user.last_name}", @post.user %>
		</div> <br/>
		<div class="social_media_sharing">
	        <div id="tweet" class="social_media"><a href="https://twitter.com/share" class="twitter-share-button" data-via="Filadelfian">Tweet</a></div>
			<div class="fb-like social_media" data-width="450" data-font="lucida grande"></div>
		</div>
	</div> 
	
	<div class="main_post_body">
		<div class="main_post_content">
		  <%= simple_format(@post.content) %>
		</div>
	</div>

	<% if @post.user == current_user %>
		<%= link_to 'Edit your piece', edit_post_path(@post), :class => "edit" %> 
	<% end %> 

	<!--<div id="disqus_thread"></div>-->
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'filadelfian'; // required: replace example with your forum shortname
        var disqus_identifier = '<%= @post.id %>';
	    var disqus_url = '<%= url_for(@post) %>';

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the<a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    

app/views/static_pages/curious.html.erb
<div class="curious">
	The Filadelfian is a literary review created at the University of Pennsylvania. <br/><br/>
	
	Its purpose is to share the most promising fiction and poetry.
</div>

app/views/static_pages/membership.html.erb
<div> 
	<div id="interested">Interested in publishing in the Filadelfian?</div> 
	
    <p class="tell_us_why">
	    Send us an email. <br/> <br/>
		Tell us why you should be here, and include the first piece you're looking to publish with us. <br/> <br/>

		hello [at] filadelfian [dot] com
    </p>

</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="content">

	<p id="notice"><%= notice %></p>

	<h1><%= @user.first_name %> <%= @user.last_name %> </h1>
    
    <% if @user.twitter != "" %>
		<div class="user_twitter">
			<%= link_to "@"+@user.twitter, "http://www.twitter.com/" + @user.twitter %>
		</div>
	<% end %>

	<div class="user_bio"><%= simple_format(@user.bio) %></div>

	<br/> <br/> <br/>

	<div class="user_posts">
		<% @user.posts.each do |post| %>
		    <div class="post">
			    <div class="post_image">
	                <%= image_tag post.image_url(:thumb) if post.image? %>
	            </div>
	            <div class="post_heading">
	                <div class="post_date">
	                    <%= Time.at(post.created_at.to_time.to_i).strftime("%B %e, %Y ") %>
	                </div> 
	                <div class="post_title purple_hover">
	                	<%= link_to post.title, post %>
	                </div>
	                <div class="post_author purple_hover">
	                  <%= link_to "#{post.user.first_name} #{post.user.last_name}", post.user %>
	                </div>
	            </div> 
	            <div class="post_content">
	            <%= simple_format(post.content[0..300] + "...") %>
		        </div>
		    </div>
	    <% end %>
	</div>

	<% if @user == current_user %>
		<%= link_to "Edit your profile", edit_registration_path(@user), :class => "edit" %>
	<% end %>

</div>